### ISSUE TITLE
Documentation: Not for production use?

### ISSUE THREAD

**Issue by tobiasbp** [cloos/docker-rt#2]
The readme says: "This image is intended for development or testing, not for production use."

What makes the image unsuitable for production use?

**Comment by cloos** [comment]
Mainly, because the images uses SQLite as database backend, which isn't suitable for production use (see https://docs.bestpractical.com/rt/latest/RT_Config.html#Database-connection).

These images are never build with production use in mind.
They should provide users a quick way to test RT and to use this images for testing their RT extensions.
